name: Trigger UI Tests

on:
  push:

jobs:
  trigger-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger UI tests workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.PAT}}
          script: |
            await github.request('POST /repos/{owner}/{repo}/dispatches', {
              owner: 'Crypted39',
              repo: 'Web-App-Automation',
              event_type: 'execute-ui-tests'
            });
